[project]
name = "thoughtful-robot"
version = "0.1.0"
description = "Robotic package sorting system for Thoughtful AI"
authors = [{name = "Victor Barbosa", email = "barbosavictor30@gmail.com"}]
requires-python = ">=3.8"
